# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "docs"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "آکادمی کوین‌ ایران - Coiniran Academy" # page title -> see ./layouts/partials/head.html

googleAnalytics = "G-6RSMTN9RB2" # if needed...

[author]
    name = "Coiniran Academy"
    email = "info@shiryakhat.net"

[params]
    description = "آکادمی کوین‌ ایران٫ دوره آموزشی بلاکچین٫ قرارداد هوشمند با سالیدیتی  - Coiniran Academy - Smartcontract Development course" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
    title = "توییتر"
    url = "https://twitter.com/coiniranacademy" # add your twitter handle
[[params.social]]
    title = "انجمن"
    url = "https://smartcontract.coiniran.com" # add your linkedin profile URL
